---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.22
  amd64: ghcr.io/home-assistant/amd64-base:3.22
  armhf: ghcr.io/home-assistant/armhf-base:3.22
  armv7: ghcr.io/home-assistant/armv7-base:3.22
  i386: ghcr.io/home-assistant/i386-base:3.22
labels:
  org.opencontainers.image.title: "PowerShell"
  org.opencontainers.image.description: "Run PowerShell scripts in Home Assistant"
  org.opencontainers.image.source: "https://github.com/woznet/WozDev-HA-Addons/tree/main/pwsh"
  org.opencontainers.image.licenses: "Apache License 2.0"
